FROM docker.io/jeffdyoung/fedora-origin-release:golang-1.10-x86_64

RUN go get github.com/prometheus/node_exporter && \
    cd ${GOPATH-$HOME/go}/src/github.com/prometheus/node_exporter && \
    make && \
    cp node_exporter /bin/node_exporter

EXPOSE 9100
USER nobody
WORKDIR /prometheus
ENTRYPOINT ["/bin/node_exporter"]
